Cargo: update dependencies
Update dependencies running `cargo update`.

Main goal here is to update futures-util to 0.3.31, due to security warning
when running cargo-audit.

```
Crate:     futures-util
Version:   0.3.28
Warning:   yanked
Dependency tree:
futures-util 0.3.28
├── reqwest 0.11.26
│   └── ue-rs 0.1.0
├── hyper 0.14.28
│   ├── reqwest 0.11.26
│   └── hyper-tls 0.5.0
│       └── reqwest 0.11.26
└── h2 0.3.26
    ├── reqwest 0.11.26
    └── hyper 0.14.28

error: 1 vulnerability found!
warning: 1 allowed warning found
```